name: Blue Scan
description: Scan your script files
#
inputs:
  tm_repository_id:
    description: Repository Id in BlueMachine
    required: true
  tm_source:
    description: The file to be sent to BlueMachine
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.tm_repository_id }}
    - ${{ inputs.tm_source }}
#
branding:
  icon: check
  color: green
